services:
  - type: web
    name: nextraceweb-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: DB_URL
        value: <sua-string-de-conexão>
      - key: JWT_SECRET
        value: <sua-chave-secreta>
